<?php

return [
    'main_menu_items' => [
        [
            'id' => 1,
            'title' => 'Dashboard',
            'slug' => 'dashboard',
            'url' => '/dashboard',
            'route' => 'filament.pages.dashboard',
            'icon' => 'fas-gauge',
            'target' => null,
            'help_text' => 'My Dashboard',
            'is_activated' => true,
        ],
        [
            'id' => 2,
            'title' => 'Blog',
            'slug' => 'blog',
            'url' => '/blog',
            'icon' => 'fas-file-lines',
            'target' => null,
            'help_text' => 'Blog Posts',
            'is_activated' => true,
        ],
        [
            'id' => 3,
            'title' => 'About',
            'slug' => 'about',
            'url' => '/about',
            'icon' => 'fas-id-card',
            'target' => null,
            'help_text' => 'About Us',
            'is_activated' => true,
        ],
        [
            'id' => 4,
            'title' => 'Events',
            'slug' => 'events',
            'url' => '/events',
            'target' => null,
            'help_text' => 'Events Calendar',
            'is_activated' => true,
        ],
        [
            'id' => 5,
            'title' => 'Quotes',
            'slug' => 'quotes',
            'url' => '/quotes',
            'target' => null,
            'help_text' => 'Request A Quote',
            'is_activated' => true,
        ],
        [
            'id' => 6,
            'title' => 'FAQ',
            'slug' => 'faq',
            'url' => '/faq',
            'target' => null,
            'help_text' => 'Frequently Asked Questions',
            'is_activated' => true,
        ],
        [
            'id' => 7,
            'title' => 'Resources',
            'slug' => 'resources',
            'url' => '/resources',
            'target' => null,
            'help_text' => 'Resources & Downloads',
            'is_activated' => true,
        ],
        [
            'id' => 8,
            'title' => 'Documentation',
            'slug' => 'documentation',
            'url' => '/documentation',
            'target' => null,
            'help_text' => 'Documentation and Guides',
            'is_activated' => true,
        ],
        [
            'id' => 9,
            'title' => 'Contact',
            'slug' => 'contact',
            'url' => '/contact',
            'target' => null,
            'help_text' => 'Contact Us',
            'is_activated' => true,
        ],
    ],
    'footer_menu_items' => [
        [
            'id' => 1,
            'title' => 'Terms of Service',
            'slug' => 'terms-of-service',
            'url' => '/terms',
            'route' => null,
            'icon' => null,
            'target' => null,
            'help_text' => 'Our Terms of Service',
            'is_activated' => true,
        ],
        [
            'id' => 2,
            'title' => 'Privacy Policy',
            'slug' => 'privacy-policy',
            'url' => '/privacy',
            'route' => null,
            'icon' => null,
            'target' => null,
            'help_text' => 'Your Rights To Privacy',
            'is_activated' => true,
        ],
    ],
    'social_menu_items' => [
        [
            'id' => 1,
            'title' => 'Facebook',
            'slug' => 'facebook',
            'url' => 'https://facebook.com/gospelfriendstexas',
            'route' => null,
            'icon' => 'fab-facebook',
            'target' => 1,
            'help_text' => 'Follow us on Facebook',
            'is_activated' => true,
        ],
        [
            'id' => 2,
            'title' => 'Instagram',
            'slug' => 'instagram',
            'url' => 'https://instagram.com/',
            'route' => null,
            'icon' => 'fab-instagram',
            'target' => 1,
            'help_text' => 'Follow us on Instagram',
            'is_activated' => true,
        ],
        [
            'id' => 3,
            'title' => 'Twitter',
            'slug' => 'twitter',
            'url' => 'https://twitter.com/',
            'route' => null,
            'icon' => 'fab-twitter',
            'target' => 1,
            'help_text' => 'Follow us on Twitter',
            'is_activated' => true,
        ],
        [
            'id' => 4,
            'title' => 'Youtube',
            'slug' => 'youtube',
            'url' => 'https://youtube.com/',
            'route' => null,
            'icon' => 'fab-youtube',
            'target' => 1,
            'help_text' => 'Follow us on Youtube',
            'is_activated' => true,
        ],
        [
            'id' => 5,
            'title' => 'TickTock',
            'slug' => 'ticktock',
            'url' => 'https://ticktock.com/',
            'route' => null,
            'icon' => 'fab-tiktok',
            'target' => 1,
            'help_text' => 'Follow us on TikTok',
            'is_activated' => true,
        ],
    ],
    'guest_menu_items' => [
        'login' => [
            'enabled' => true,
            'url' => '/login',
            'route_name' => 'login',
            'text' => 'Log In',
        ],
        'register' => [
            'enabled' => true,
            'url' => '/register',
            'route_name' => 'register',
            'text' => 'Register',
        ],
    ],
];